id: P007854
initial_creation_type: ocr
source_metadata:
  id: bdr:W8LS17445
  title: རྒྱུད་སྡེ་བཞིའི་སྡོམ་ཚིག་རྒྱུད་དོན་བལྟ་བའི་མིག་འབྱེད།
  author: ''
  volumes:
    67ee968e555846f8907ee1273b032e14:
      image_group_id: I8LS17454
      title: ''
      volume_number: 1
      total_pages: 84
ebook_metadata:
  title: རྒྱུད་སྡེ་བཞིའི་སྡོམ་ཚིག་རྒྱུད་དོན་བལྟ་བའི་མིག་འབྱེད།
  author: ''
  sku: P007854
  cover: cover.jpg
  layers:
  - pagination
