id: IEA9E41E5
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-21T21:01:53+00:00'
last_modified: '2022-06-09T06:37:52.666469+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W8LS17445
  title: རྒྱུད་སྡེ་བཞིའི་སྡོམ་ཚིག་རྒྱུད་དོན་བལྟ་བའི་མིག་འབྱེད།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    04F9:
      image_group_id: I8LS17454
      title: Volume 1 of rgyud sde bzhi'i sdom tshig rgyud don blta ba'i mig 'byed/
      total_pages: 84
      order: 1
      base_file: 04F9.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
